

export var newSampleEvaluationText = {
  readingEndIndex: {
    paragraphIndex: 0, // -1
    wordIndex:74, // -1
  },
  paragraphs: [
    {
      key: 'fake',
      words: [

        {
          word: 'I',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'just',
          wordDeleted: true,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'didn\'t',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: 'jus',
        },
        {
          word: 'feel',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'like',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'doing',
          wordDeleted: true,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'anything',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'much',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'for',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'the',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'rest',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'of',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'the',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'day.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'Mike',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'went',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'out',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'with',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'his',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'friends',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'so',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'I',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'stayed',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'up',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'in',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'my',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'room',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'and',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'played,',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'building',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'a',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'neat',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: 'cast',
        },
        {
          word: 'castle',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'and',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'fighting',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'a',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'war',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'with',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: 'plas with',
        },
        {
          word: 'the',
          wordDeleted: true,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'plastic',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: 'kings in that',
        },
        {
          word: 'knights',
          wordDeleted: true,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'my',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'mother',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'had',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'gotten',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'for',
          wordDeleted: true,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'me.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'I',
          wordDeleted: true,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'made',
          wordDeleted: true,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'one',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: 'made',
        },
        {
          word: 'Merlin',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'The',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: 'majis the',
        },
        {
          word: 'Magician.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'That',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'was',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'Saturday.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'The',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'next',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'morning,',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'Sunday,',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'we',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'had',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'our',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'usual',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'family',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'breakfast,',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'about',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'the',
          wordDeleted: true,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'only',
          wordDeleted: true,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'time',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'the',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: 'the brunch',
        },
        {
          word: 'bunch',
          wordDeleted: true,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'of',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'us',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'get',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'to',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'sit',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'down',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'and',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'take',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'as',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'long',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'as',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'we',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'want.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'About',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'halfway',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'through',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'my',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'mother',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'said,',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: '\"I',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'have',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'an',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'idea.\"',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },

      ],
    },

    {
      key: 'fake2',
      words: [

        {
          word: '\"Maybe',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'we',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'should',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'get',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'you',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'another',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'bike,\"',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'she',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'said.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: '\"Mr.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'Bullen',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'is',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'open',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'on',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'Sundays.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'I\'m',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'sure',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'we',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'could',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'find',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'one.\"',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: '\"What',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'happens',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'if',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'he',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'finds',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'the',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'one',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'he',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'lost?\"',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'asked',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'Mike.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: '\"I',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'doubt',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'very',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'much',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'if',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'he',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'will,\"',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'my',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'father',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'said.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: '\"Mr.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'Podler',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'said',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'he',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'saw',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'someone',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'with',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'it,\"',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'I',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'reminded',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'him.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: '\"We',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'all',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'know',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'about',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'Mr.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'Podler,\"',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'was',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'my',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'father\'s',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'answer',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'to',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'that.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: '\"Someday',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'I\'ll',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'tell',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'you',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'about',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'the',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'ghosts',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'he',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'saw',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'in',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'City',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'Hall.\"',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: '\"Don\'t',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'you',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'want',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'a',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'bike?\"',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'my',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'mother',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'asked.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'Mike\'s',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'question',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'was',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'the',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'right',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'one.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: '\"What',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'happens',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'if',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'my',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'old',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'one',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'turns',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'up?\"',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'I',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'asked.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: '\"We\'ll',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'worry',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'about',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'that',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'if',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'it',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'happens,\"',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'suggested',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'my',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'mom.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
      ],
    },

    {
      key: 'fake3',
      words: [


        {
          word: '\"It\'s',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'up',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'to',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'you.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'We',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'can',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'get',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'one',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'if',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'you',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'want.\"',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: '\"If',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'I',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'do',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'get',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'a',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'new',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'one,',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'does',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'that',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'mean',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'I',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'have',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'to',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'stop',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'looking',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'for',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'the',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'old',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'one?\"',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'I',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'wanted',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'to',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'know.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: '\"I',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'don\'t',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'see',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'much',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'point',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'in',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'looking,\"',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'said',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'my',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'father.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: '\"But',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'if',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'you',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'want',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'to,',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'there\'s',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'no',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'one',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'saying',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'you',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'can\'t.\"',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: '\"Okay,',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'I\'ll',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'get',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'one.\"',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: '\"I\'ll',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'go',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'with',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'you,\"',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'Mike',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'said',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'suddenly.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: '\"I',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'need',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'some',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'radio',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'parts.\"',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'It',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'was',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'eleven',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'when',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'my',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'mother,',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'Mike',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'with',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'his',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'radio',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'parts',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'box,',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'and',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'I',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'got',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'into',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'the',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'car',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'and',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'drove',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'to',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'Mr.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'Bullen\'s',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'junk',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'yard',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'a',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'little',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'way',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'out',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'of',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'town.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },

      ],
    },

    {
      key: 'fake4',
      words: [


        {
          word: 'My',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'mother',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'has',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'always',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'had',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'a',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'particular',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'liking',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'for',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'Mr.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'Bullen,',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'and',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'since',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'she',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'likes',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'junk,',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'it\'s',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'not',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'hard',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'to',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'see',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'why.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'The',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'lot',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'is',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'something',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'kind',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'of',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'hard',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'to',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'describe.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'It',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'has',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'just',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'about',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'everything',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'in',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'the',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'world',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'piled',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'up',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'in',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'heaps,',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'piled',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'up',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'so',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'much',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'that',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'it\'s',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'hard',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'to',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'find',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'anything.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'There',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'are',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'some',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'sections,',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'such',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'as',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'shutters,',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'or',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'bathtubs,',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'but',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'aside',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'from',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'those,',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'you',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'just',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'have',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'to',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'go',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'looking',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'and',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'there',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'are',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'more',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'hiding',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'places',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'there',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'than',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'anywhere',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
        {
          word: 'else.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
        },
      ],
    },
  ],
}



