export var newSampleEvaluationText = {
  readingEndIndex: {
    paragraphIndex: 0, // -1
    wordIndex:74, // -1
  },
  paragraphs: [
	{
		key: 'fake_key_0',
		words: [
		{
			word: 'Nick',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'was',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'looking',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'at',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'his',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'book.',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'His',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'mom',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'came',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'in',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'and',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'said,',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: '\"It’s',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'time',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'for',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'bed.\"',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: '\"Okay,',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'Mom,\"',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'said',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'Nick.',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
	],
	},
	{
		key: 'fake_key_1',
		words: [
		{
			word: 'Nick',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'put',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'on',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'his',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'pajamas.',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'He',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'washed',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'his',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'face',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'and',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'brushed',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'his',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'teeth.',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'He',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'was',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'ready',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'for',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'bed.',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
	],
	},
	{
		key: 'fake_key_2',
		words: [
		{
			word: '\"Will',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'you',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'read',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'me',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'a',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'story?\"',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'Nick',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'asked',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'his',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'mom.',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'Mom',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'read',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'the',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'story',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'to',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'Nick.',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'Nick',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'liked',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'the',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'story',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'about',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'the',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'magic',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'fish.',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
	],
	},
	{
		key: 'fake_key_3',
		words: [
		{
			word: 'When',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'the',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'story',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'was',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'over,',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'Nick\'s',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'mom',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'turned',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'off',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'the',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'light.',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: '\"Good',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'night,',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'Nick,\"',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'his',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'mom',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'said.',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
	],
	},
	{
		key: 'fake_key_4',
		words: [
		{
			word: '\"Will',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'you',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'turn',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'on',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'the',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'nightlight?\"',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'asked',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'Nick.',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: '\"Okay,',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'Nick,\"',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'his',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'mom',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'said.',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'She',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'turned',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'it',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'on.',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
	],
	},
	{
		key: 'fake_key_5',
		words: [
		{
			word: '\"Good',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'night,',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'Nick,\"',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'his',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'mom',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'said.',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: '\"Now',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'it’s',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'time',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'to',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'go',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'to',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'sleep.\"',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: '\"I',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'can’t',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'go',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'to',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'sleep,\"',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'said',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'Nick.',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: '\"I',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'will',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'give',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'you',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'a',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'good',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'night',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'kiss,\"',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'said',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'Nick\'s',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'mom',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
	],
	},
	{
		key: 'fake_key_6',
		words: [
		{
			word: '\"I',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'can’t',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'go',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'to',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'sleep,\"',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'said',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'Nick.',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: '\"Will',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'you',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'open',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'the',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'door?\"',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'he',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'asked.',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'Nick’s',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'mom',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'opened',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'the',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'door.',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'Light',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'came',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'into',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'the',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'room.',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
	],
	},
	{
		key: 'fake_key_7',
		words: [
		{
			word: '\"Good',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'night,',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'Nick,\"',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'his',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'mom',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'said.',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: '\"Go',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'to',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'sleep',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'now.\"',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: '\"I',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'can\'t',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'go',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'to',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'sleep,\"',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'said',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'Nick.',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: '\"Something',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'is',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'missing.\"',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
	],
	},
	{
		key: 'fake_key_8',
		words: [
		{
			word: 'He',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'looked',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'around',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'the',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'room.',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'Something',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'came',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'in',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'the',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'door.',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: '\"Wags!',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'You’re',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'late,\"',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'said',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'Nick.',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: '\"Now',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'we',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'can',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'go',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'to',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'sleep.',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
	],
	},
	{
		key: 'fake_key_9',
		words: [
		{
			word: '\"Good',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'night,',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'Nick,\"',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'said',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'Mom.',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: '\"Good',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'night,',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'Wags.\"',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: '\"Good',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'night,',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'Mom,\"',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'said',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
		{
			word: 'Nick.',
			wordDeleted: false,
			substituteWord: null,
			addAfterWord: null,
		},
	],
	},
  ],
}
