





// <div className={styles.textContainer}>

//             <div className={styles.textParagraph}>
//               <span className={styles.textWord}>When</span><span className={styles.textWord}>&nbsp;&nbsp;</span><span className={styles.textWord}>the</span> <span className={styles.textWord}>moon</span> <span className={styles.textWord}>is</span> <span className={styles.textWord}>high</span> <span className={styles.textWord}>and</span> <span className={styles.textWord}>the</span> <span onMouseEnter={this.mouseEnter} onMouseLeave={this.mouseLeave}>stars</span> <span className={styles.textWord}>are</span> <span className={styles.textWord}>bright,</span> <span className={styles.textWord}>Daddy</span> <span className={styles.textWord}>tells</span> <span className={styles.textWord}>me,</span> <span className={styles.textWord}>"It's</span> <span className={styles.textWord}>a</span> <span className={styles.textWord}>firefly</span> <span className={styles.textWord}>night!"</span>
//             </div>

//             <div className={styles.textParagraph}>
//               I hop off the porch. I feel the air. It warms my legs and tosses my hair.
//             </div>

//           </div>




// export const sampleEvaluationText = {
//   paragraphs: [
//     "This is paragraph number 1 blah balh asdf asdfasf sadfkads ljkasdf lkjasdf asdfljka faslkdjf asldkjf dsf asdf asdlfkj asdflkj adas",
//     "paragraph 2 adf sdklf slk lsdflk;a eow w89w asdklfds slkdfljd slkdj sdklfj sl;ddl s  d dss dsfd fs fsdfkls falkssaflfsdaf",
//     "and finally nubmer 3 aslfkj sdlfkjsdf dsfsf sdfsdf sdfs df",
//   ],
// }

export var sampleEvaluationText = {
  paragraphs: [
    {
      key: 'sViGwBGcDZ',
      words: [
        {
          key: 'rWBhu2a3xf',
          word: 'When',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '9vQT6vb82l',
          word: 'the',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '0a1Ggjrm0U',
          word: 'moon',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: 'added',
          correctionValue: '',
          isEnd: false,
        },
        {
          key: 'J4WWTi6GCl',
          word: 'is',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: 'oBymEw0AYZ',
          word: 'high',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: 'BX5BjZiDn5',
          word: 'and',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: 'GG7vquRMy5',
          word: 'the',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '5qfijjmweA',
          word: 'stars',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '7vbhVEsR7a',
          word: 'are',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: 'P48btnT7fJ',
          word: 'bright,',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: 'wvFJGu6NiR',
          word: 'Daddy',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: 'zm9644WhbN',
          word: 'tells',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: 'x4IxSK8kJj',
          word: 'me,',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: 'gGVbaaMEzc',
          word: '"It\'s',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: 'ljGmEK8RfA',
          word: 'a',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: 'zGAtiZq4ws',
          word: 'firefly',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: 'YMjd75sYYJ',
          word: 'night!"',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
      ],
    },

    {
      key: '2u9V1wTw54',
      words: [
        {
          key: '',
          word: 'I',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'hop',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'off',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'the',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'porch.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'I',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'feel',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'the',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'air.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'It',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'warms',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'my',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: 'is',
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'legs',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'and',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'tosses',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'my',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'hair.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
      ],
    },

    {
      key: 'U5eHTn5XAx',
      words: [
        {
          key: '',
          word: 'Grass',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'tickles',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'my',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'toes.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'I',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'run',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'through',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'the',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'yard.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'I',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'chase',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'fireflies',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'to',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'put',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'in',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'my',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'jar.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
      ],
    },

    {
      key: 'v0zMHht0xj',
      words: [
        {
          key: '',
          word: 'Fireflies',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'shine.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'All',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'of',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'them',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'glow.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'I',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'race',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'to',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'show',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'Daddy',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'their',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'dancing',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'light',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'show.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
      ],
    },

    {
      key: '5CMPpma5lI',
      words: [
        {
          key: '',
          word: 'They',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'fly',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'away',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'quickly.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'They',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'sparkle',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'and',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'shine.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'I',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'love',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'catching',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'fireflies,',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'but',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'they',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'are',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'not',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'mine.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
      ],
    },

    {
      key: 'qN9r5TjgRL',
      words: [
        {
          key: '',
          word: 'We',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'walk',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'back',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'to',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'the',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'home.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'I',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'hold',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'Daddy\'s',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'hand',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'tight.',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'I',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'ask',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'him',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: '"Will',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'tomorrow',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'be',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'a',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'firefly',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
        {
          key: '',
          word: 'night?"',
          wordDeleted: false,
          substituteWord: null,
          addAfterWord: null,
          correctionValue: '',
          isEnd: false,
        },
      ],
    },
  ],
}
 





